name: Actionlint

on:
  pull_request:
    paths:
      - '.github/workflows/**/*.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rwxrob/actionlint@v1
