name: React build

on:
  workflow_call:

    inputs:
      run-storybook:
        required: false
        type: boolean
        default: false

      publish:
        required: false
        type: boolean
        default: false

      yarn:
        required: false
        type: boolean
        default: false

    secrets:
      GITHUB_PACKAGE_TOKEN:
        required: false

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@easylife365'

      - name: Install Yarn v1
        if: ${{ inputs.yarn }}
        run: npm install -g yarn@1

      - name: Install dependencies
        if: ${{ inputs.yarn }}
        run: yarn install --frozen-lockfile
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Install Dependencies
        if: ${{ !inputs.yarn }}
        run: npm ci
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - uses: EasyLife365/get-version-action@v1
        if: ${{ inputs.publish }}
        id: version

      - name: Set version (npm)
        if: ${{ inputs.publish && !inputs.yarn }}
        run: npm version ${{ steps.version.outputs.versionWithoutV }} --no-git-tag-version

      - name: Set version (yarn)
        if: ${{ inputs.publish && inputs.yarn }}
        run: yarn version --new-version ${{ steps.version.outputs.versionWithoutV }} --no-git-tag-version
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Build (npm)
        if: ${{ !inputs.yarn }}
        run: npm run build --if-present
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Build (yarn)
        if: ${{ inputs.yarn }}
        run: yarn build
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Install Playwright
        if: ${{ inputs.run-storybook }}
        run: npx playwright install --with-deps

      - name: Build Storybook (npm)
        if: ${{ inputs.run-storybook && !inputs.yarn }}
        run: npm run storybook:export
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Build Storybook (yarn)
        if: ${{ inputs.run-storybook && inputs.yarn }}
        run: yarn storybook:export
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Serve Storybook and run tests (npm)
        if: ${{ inputs.run-storybook && !inputs.yarn }}
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-coverage"
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - name: Serve Storybook and run tests (yarn)
        if: ${{ inputs.run-storybook && inputs.yarn }}
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && yarn test-coverage"
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - uses: dorny/test-reporter@v1
        if: always() && inputs.run-storybook
        with:
          name: Test Details                 
          path: junit.xml                     
          reporter: jest-junit

      - name: Publish packages
        if: ${{ inputs.publish }}
        run: npm publish
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
