name: React build

on:
  workflow_call:

    inputs:
      run-storybook:
        required: false
        type: boolean
        default: false

      publish:
        required: false
        type: boolean
        default: false

    secrets:
      GITHUB_PACKAGE_TOKEN:
        required: false

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@easylife365'

      - name: Install Dependencies
        run: npm ci
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}

      - uses: EasyLife365/get-version-action@v1
        if: ${{ inputs.publish }}
        id: version

      - name: Set version
        if: ${{ inputs.publish }}
        run: npm version ${{ steps.version.outputs.versionWithoutV }} --no-git-tag-version

      - run: npm run build --if-present

      - name: Install Playwright
        if: ${{ inputs.run-storybook }}
        run: npx playwright install --with-deps

      - name: Build Storybook
        if: ${{ inputs.run-storybook }}
        run: npm run storybook:export

      - name: Serve Storybook and run tests
        if: ${{ inputs.run-storybook }}
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && npm run test-coverage"

      - uses: dorny/test-reporter@v1
        if: always() && inputs.run-storybook
        with:
          name: Test Details                 
          path: junit.xml                     
          reporter: jest-junit

      - name: Publish packages
        if: ${{ inputs.publish }}
        run: npm publish
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
