name: SPA Build

on:
  workflow_call:
    inputs:
      app-location:
        description: The project location of the app
        required: true
        type: string
      app-target:
        description: The project target of the app
        required: true
        type: string
      app-artifact:
        description: The project artifact of the app
        required: true
        type: string

    secrets:
      package-token: 
        description: The nuget token to restore the packages
        required: true

env:
  CI: false

permissions:
   id-token: write
   contents: read

jobs:
  build:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ${{ inputs.app-location }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.package-token }}

      - uses: EasyLife365/get-version-action@v1
        id: version

      - name: Set version
        run: npm version ${{ steps.version.outputs.versionWithoutV }} --no-git-tag-version
        working-directory: ${{ inputs.app-location }}

      - name: Build
        run: "npm run build:${{ inputs.app-target }}"
        working-directory: ${{ inputs.app-location }}

      - name: Upload build app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app-artifact }}
          path: "${{ inputs.app-location }}/dist"
          include-hidden-files: true
          retention-days: 15
